name: getx_tulang_cf
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.0 <3.0.0"

# dependency atau library
dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  lottie: 1.3.0
  flutter_svg: 1.0.3
  intl: 0.17.0
  font_awesome_flutter: 10.1.0
  indent: ^2.0.0
  http: 0.13.4
  cool_dropdown: ^1.4.1
  drop_down_list: ^0.0.2
  get_storage: ^2.0.3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lotties/
    - assets/icons/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-SemiBold.ttf
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli-SemiBold.ttf
